[package]
name = "zillanote"
version = "0.2.2"
edition = "2024"

[build-dependencies]
tauri-build = { workspace = true }

[dependencies]
engine = { workspace = true }

chrono = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tauri = { workspace = true, features = ["macos-private-api", "tray-icon", "image-png"] }
tauri-plugin-dialog = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "sync"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
